services:
  - type: web
    name: easybill-backend
    env: node
    branch: main
    plan: free
    region: oregon
    root: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
